[package]
name = "hermes_optimizer"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
geo = "0.30.0"
jiff = "0.2.15"
parking_lot = "0.12.4"
rand = "0.9.1"
rstar = "0.12.2"
tracing = "0.1.41"
uuid = { features = ["v4"], version = "1.17.0" }
