[workspace]
resolver = "2"
members = ["hermes", "hermes_api", "hermes_core", "hermes_matrix", "hermes_optimizer"]


[profile.release]
debug = true

[build]
rustflags = ["-Csymbol-mangling-version=v0"]
