[package]
name = "hermes_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
hermes_core = { version = "0.1.0", path = "../hermes_core" }
tower = { version = "0.5.2" }
serde_json = "1.0.140"
geojson = "0.24.2"
tower-http = { version = "0.6.2", features = ["cors"] }
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
