[package]
name = "hermes_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
hermes_core = { version = "0.1.0", path = "../hermes_core" }
tower = "0.5.2"
serde_json = "1.0.140"

