[package]
name = "hermes_matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
geo-types = "0.7.18"
reqwest = { version = "0.12.26", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = "1.48.0"
